project:
  type: website
  output-dir: docs

website:
  title: "Anthony Zorney"
  favicon: photos/favicon.png 
  navbar:
    left:
      - href: index.qmd
        text: Home
      - education.qmd
      - experience.qmd
      - projects.qmd
      - skills.qmd
      - photography.qmd

format:
  html:
    theme: sandstone
    css: styles.css 
    toc: true

editor: visual
