project:
  type: website
  output-dir: docs

website:
  title: "Anthony Zorney"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - education.qmd
      - experience.qmd
      - skills.qmd
      - projects.qmd
      - photography.qmd

format:
  html:
    theme: cosmo
    toc: true

editor: visual
